name: Biru C. Sainju
description: Personal website
url: "http://birusainju.com.np"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: false

# Site settings
permalink: /blog/:title/
relative_permalinks: false
highlighter: pygments
rel: "canonical"
source: ./
destination: ../master
timezone: Asia/Kathmandu



paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true

author:
  name: Biru C. Sainju
  email: sainju.biru@gmail.com
  github: thugliffe
  twitter: birusainju
  #pinterest: asd123
  linkedin: birusainju
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:


## Publications and citations
#scholar:
#  style: apa
#  locale: en

# sort_by: none
#  order: ascending

  #source: ./_publications
  #bibliography: citations.bib
  #bibliography_template: "{{reference}}"

#  replace_strings: true
#  join_strings:    true

#  details_dir:    bibliography
#  details_layout: bibtex.html
#  details_link:   Details

#  query: "@*"
